"""
Bootstrap confidence intervals for regime map controllability scores.

Resamples per-seed results (5 seeds × 8 samples = 40 total per condition)
to compute 95% CIs for each property's controllability percentage.
Also re-runs the regime predictor with CIs on correlation coefficients.

Requires: regime_map_results.json (generated by test_regime_map.py with cfg_scale=2.0)
"""

import json
import numpy as np
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent


def bootstrap_controllability(cond_results, uncond_key='unconditioned',
                              n_bootstrap=10000, ci=0.95, rng_seed=42):
    """Compute bootstrap CIs for controllability scores.

    Returns dict: property -> {mean, ci_low, ci_high, best_condition, regime}
    """
    rng = np.random.RandomState(rng_seed)
    prop_names = list(cond_results[uncond_key][0].keys())
    n_samples = len(cond_results[uncond_key])
    alpha = (1 - ci) / 2

    results = {}
    for pname in prop_names:
        uncond_vals = np.array([p[pname] for p in cond_results[uncond_key]])

        best_shift_pct = 0.0
        best_cond = 'none'
        best_boot_shifts = None

        for cond_name, cond_props in cond_results.items():
            if cond_name == uncond_key:
                continue
            cond_vals = np.array([p[pname] for p in cond_props])

            boot_shifts = np.zeros(n_bootstrap)
            for b in range(n_bootstrap):
                idx_u = rng.randint(0, n_samples, n_samples)
                idx_c = rng.randint(0, len(cond_vals), len(cond_vals))
                u_mean = uncond_vals[idx_u].mean()
                c_mean = cond_vals[idx_c].mean()
                shift = abs(c_mean - u_mean) / max(abs(u_mean), 0.001) * 100
                boot_shifts[b] = shift

            observed = abs(cond_vals.mean() - uncond_vals.mean()) / max(abs(uncond_vals.mean()), 0.001) * 100
            if observed > best_shift_pct:
                best_shift_pct = observed
                best_cond = cond_name
                best_boot_shifts = boot_shifts

        ci_low = float(np.percentile(best_boot_shifts, alpha * 100))
        ci_high = float(np.percentile(best_boot_shifts, (1 - alpha) * 100))

        if ci_low > 100:
            regime = "CONTROLLABLE"
        elif ci_high < 20:
            regime = "UNRESPONSIVE"
        elif best_shift_pct > 100:
            regime = "CONTROLLABLE"
        elif best_shift_pct > 20:
            regime = "APPROACHABLE"
        else:
            regime = "UNRESPONSIVE"

        results[pname] = {
            'controllability_pct': round(best_shift_pct, 2),
            'ci_low': round(ci_low, 2),
            'ci_high': round(ci_high, 2),
            'best_condition': best_cond,
            'regime': regime,
            'regime_confident': ci_low > 100 or ci_high < 20,
        }

    return results


def bootstrap_correlation(x, y, n_bootstrap=10000, ci=0.95, rng_seed=42):
    """Bootstrap CI for Spearman correlation."""
    from scipy.stats import spearmanr
    rng = np.random.RandomState(rng_seed)
    n = len(x)
    alpha = (1 - ci) / 2

    observed_r, observed_p = spearmanr(x, y)
    boot_r = np.zeros(n_bootstrap)
    for b in range(n_bootstrap):
        idx = rng.randint(0, n, n)
        r, _ = spearmanr(x[idx], y[idx])
        boot_r[b] = r if not np.isnan(r) else 0.0

    return {
        'rho': round(float(observed_r), 4),
        'p': round(float(observed_p), 4),
        'ci_low': round(float(np.percentile(boot_r, alpha * 100)), 4),
        'ci_high': round(float(np.percentile(boot_r, (1 - alpha) * 100)), 4),
    }


def main():
    results_path = PROJECT_ROOT / "outputs" / "regime_map_results.json"
    if not results_path.exists():
        print("ERROR: regime_map_results.json not found. Run test_regime_map.py first.")
        return

    with open(results_path) as f:
        data = json.load(f)

    cond_results = data['conditions']
    print("=" * 80)
    print("BOOTSTRAP CONFIDENCE INTERVALS FOR REGIME MAP")
    print("=" * 80)

    boot_results = bootstrap_controllability(cond_results)

    print(f"\n{'Property':<22} {'Ctrl%':>8} {'95% CI':>18} {'Regime':<15} {'Confident':>10}")
    print("-" * 80)
    for pname, r in boot_results.items():
        ci_str = f"[{r['ci_low']:.1f}%, {r['ci_high']:.1f}%]"
        conf_str = "YES" if r['regime_confident'] else "no"
        print(f"{pname:<22} {r['controllability_pct']:>7.1f}% {ci_str:>18} {r['regime']:<15} {conf_str:>10}")

    # Bootstrap correlations for predictor
    print(f"\n{'=' * 80}")
    print("BOOTSTRAP CORRELATIONS (emergent properties)")
    print(f"{'=' * 80}")

    predictor_path = PROJECT_ROOT / "outputs" / "regime_predictor_results.json"
    if predictor_path.exists():
        with open(predictor_path) as f:
            pred_data = json.load(f)

        emergent = [p for p in pred_data['feature_table'] if p['has_direct_cond'] == 0]
        if len(emergent) >= 4:
            cvs = np.array([p['training_cv'] for p in emergent])
            ctrls = np.array([boot_results[p['property']]['controllability_pct'] for p in emergent])
            corr_cv = bootstrap_correlation(cvs, ctrls)
            print(f"\n  Training CV vs Controllability:  rho={corr_cv['rho']}, "
                  f"p={corr_cv['p']}, 95% CI=[{corr_cv['ci_low']}, {corr_cv['ci_high']}]")

            corrs = np.array([p['effective_frequency'] for p in emergent])
            corr_freq = bootstrap_correlation(corrs, ctrls)
            print(f"  Proxy Corr vs Controllability:  rho={corr_freq['rho']}, "
                  f"p={corr_freq['p']}, 95% CI=[{corr_freq['ci_low']}, {corr_freq['ci_high']}]")

    # Save
    output = {
        'n_bootstrap': 10000,
        'ci_level': 0.95,
        'properties': boot_results,
    }
    out_path = PROJECT_ROOT / "outputs" / "bootstrap_results.json"
    with open(out_path, 'w') as f:
        json.dump(output, f, indent=2)
    print(f"\nResults saved to {out_path}")


if __name__ == "__main__":
    main()
